2025-07-03 20:46:29,095 - WARNING -  * Debugger is active!
2025-07-03 20:46:29,099 - INFO -  * Debugger PIN: 544-602-625
2025-07-03 20:50:13,939 - INFO -  * Detected change in '/home/debian/ironing/app.py', reloading
2025-07-03 20:51:34,258 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 20:51:34,260 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 20:51:34,269 - INFO -  * Restarting with stat
2025-07-03 20:51:39,578 - WARNING -  * Debugger is active!
2025-07-03 20:51:39,582 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 20:51:47,294 - INFO - 192.168.1.5 - - [03/Jul/2025 20:51:47] "GET /forum HTTP/1.1" 200 -
2025-07-03 20:51:50,568 - INFO - 192.168.1.5 - - [03/Jul/2025 20:51:50] "GET / HTTP/1.1" 200 -
2025-07-03 20:51:50,738 - INFO - 192.168.1.5 - - [03/Jul/2025 20:51:50] "GET /static/ironing.jpg HTTP/1.1" 200 -
2025-07-03 20:53:01,902 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 20:53:01,904 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 20:53:01,912 - INFO -  * Restarting with stat
2025-07-03 20:53:07,185 - WARNING -  * Debugger is active!
2025-07-03 20:53:07,196 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 20:53:30,938 - INFO - 192.168.1.5 - - [03/Jul/2025 20:53:30] "GET / HTTP/1.1" 200 -
2025-07-03 20:53:31,092 - INFO - 192.168.1.5 - - [03/Jul/2025 20:53:31] "GET /static/ironing.jpg HTTP/1.1" 200 -
2025-07-03 20:53:35,014 - INFO - 192.168.1.5 - - [03/Jul/2025 20:53:35] "GET /admin HTTP/1.1" 200 -
2025-07-03 20:53:40,194 - INFO - 192.168.1.5 - - [03/Jul/2025 20:53:40] "GET /admin HTTP/1.1" 200 -
2025-07-03 20:54:34,291 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 20:54:34,293 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 20:54:34,303 - INFO -  * Restarting with stat
2025-07-03 20:54:39,576 - WARNING -  * Debugger is active!
2025-07-03 20:54:39,581 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 20:54:49,007 - INFO - 192.168.1.5 - - [03/Jul/2025 20:54:49] "GET /admin HTTP/1.1" 200 -
2025-07-03 20:55:02,637 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:02] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:05,075 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:05] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:05,121 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:05] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:06,338 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:06] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:06,384 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:06] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:07,364 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:07] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:07,409 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:07] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:08,450 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:08] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:08,496 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:08] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:09,178 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:09] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:09,225 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:09] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:09,905 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:09] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:09,950 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:09] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:11,148 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:11] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:11,193 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:11] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:12,732 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:12] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:12,778 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:12] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:15,114 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:15] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:15,162 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:15] "GET /submit HTTP/1.1" 200 -
2025-07-03 20:55:49,009 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:49] "[32mGET /capture HTTP/1.1[0m" 302 -
2025-07-03 20:55:49,055 - INFO - 112.199.132.115 - - [03/Jul/2025 20:55:49] "GET /submit HTTP/1.1" 200 -
2025-07-03 21:03:08,233 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:03:08,235 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:03:08,244 - INFO -  * Restarting with stat
2025-07-03 21:03:13,520 - WARNING -  * Debugger is active!
2025-07-03 21:03:13,524 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:03:32,243 - INFO - 192.168.1.5 - - [03/Jul/2025 21:03:32] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:03:58,042 - INFO - 192.168.1.5 - - [03/Jul/2025 21:03:58] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:04:09,569 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:09] "GET / HTTP/1.1" 200 -
2025-07-03 21:04:09,756 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:09] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-03 21:04:12,334 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:12] "GET /login HTTP/1.1" 200 -
2025-07-03 21:04:14,298 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:14] "GET /register HTTP/1.1" 200 -
2025-07-03 21:04:22,772 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:22] "[32mPOST /register HTTP/1.1[0m" 302 -
2025-07-03 21:04:22,936 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:22] "GET /login HTTP/1.1" 200 -
2025-07-03 21:04:26,104 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:26] "[32mPOST /login HTTP/1.1[0m" 302 -
2025-07-03 21:04:26,449 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:26] "GET / HTTP/1.1" 200 -
2025-07-03 21:04:26,650 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:26] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-03 21:04:31,844 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:31] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:04:34,074 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:34] "[35m[1mPOST /promote HTTP/1.1[0m" 500 -
2025-07-03 21:04:34,313 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:34] "GET /promote?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-07-03 21:04:34,352 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:34] "GET /promote?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-07-03 21:04:34,533 - INFO - 192.168.1.5 - - [03/Jul/2025 21:04:34] "GET /promote?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-07-03 21:05:47,689 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:05:47,691 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:05:47,699 - INFO -  * Restarting with stat
2025-07-03 21:05:52,993 - WARNING -  * Debugger is active!
2025-07-03 21:05:53,002 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:06:02,263 - INFO - 192.168.1.5 - - [03/Jul/2025 21:06:02] "[35m[1mPOST /promote HTTP/1.1[0m" 500 -
2025-07-03 21:06:02,511 - INFO - 192.168.1.5 - - [03/Jul/2025 21:06:02] "GET /promote?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-07-03 21:06:02,557 - INFO - 192.168.1.5 - - [03/Jul/2025 21:06:02] "GET /promote?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-07-03 21:06:02,729 - INFO - 192.168.1.5 - - [03/Jul/2025 21:06:02] "GET /promote?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-07-03 21:06:33,934 - INFO - 192.168.1.5 - - [03/Jul/2025 21:06:33] "GET /about HTTP/1.1" 200 -
2025-07-03 21:09:42,027 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:09:42,030 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:09:42,038 - INFO -  * Restarting with stat
2025-07-03 21:09:47,397 - WARNING -  * Debugger is active!
2025-07-03 21:09:47,401 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:09:55,161 - INFO - 192.168.1.5 - - [03/Jul/2025 21:09:55] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:09:55,450 - INFO - 192.168.1.5 - - [03/Jul/2025 21:09:55] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:09:58,420 - INFO - 192.168.1.5 - - [03/Jul/2025 21:09:58] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:09:58,550 - INFO - 192.168.1.5 - - [03/Jul/2025 21:09:58] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:00,547 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:00] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:10:00,665 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:00] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:01,600 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:01] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:10:01,720 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:01] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:02,557 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:02] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:10:02,725 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:02] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:04,700 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:04] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:06,080 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:06] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:16,949 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:16] "GET /about HTTP/1.1" 200 -
2025-07-03 21:10:26,558 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:26] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:10:26,683 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:26] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:27,223 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:27] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:10:27,355 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:27] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:10:27,885 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:27] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:10:28,062 - INFO - 192.168.1.5 - - [03/Jul/2025 21:10:28] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:13:12,110 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:13:12,112 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:13:12,121 - INFO -  * Restarting with stat
2025-07-03 21:13:17,424 - WARNING -  * Debugger is active!
2025-07-03 21:13:17,434 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:13:47,368 - INFO - 192.168.1.5 - - [03/Jul/2025 21:13:47] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:14:06,671 - INFO - 192.168.1.5 - - [03/Jul/2025 21:14:06] "[32mPOST /promote HTTP/1.1[0m" 302 -
2025-07-03 21:14:06,802 - INFO - 192.168.1.5 - - [03/Jul/2025 21:14:06] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:14:31,336 - INFO - 192.168.1.5 - - [03/Jul/2025 21:14:31] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:16:13,488 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:16:13,490 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:16:13,499 - INFO -  * Restarting with stat
2025-07-03 21:16:18,785 - WARNING -  * Debugger is active!
2025-07-03 21:16:18,794 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:16:25,762 - INFO - 192.168.1.5 - - [03/Jul/2025 21:16:25] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:27:05,758 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:27:05,760 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:27:05,769 - INFO -  * Restarting with stat
2025-07-03 21:27:11,052 - WARNING -  * Debugger is active!
2025-07-03 21:27:11,062 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:27:20,050 - INFO - 192.168.1.5 - - [03/Jul/2025 21:27:20] "[35m[1mGET /admin HTTP/1.1[0m" 500 -
2025-07-03 21:27:20,298 - INFO - 192.168.1.5 - - [03/Jul/2025 21:27:20] "GET /admin?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-07-03 21:27:20,355 - INFO - 192.168.1.5 - - [03/Jul/2025 21:27:20] "GET /admin?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-07-03 21:27:20,563 - INFO - 192.168.1.5 - - [03/Jul/2025 21:27:20] "GET /admin?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-07-03 21:28:25,290 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:28:25,292 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:28:25,301 - INFO -  * Restarting with stat
2025-07-03 21:28:30,589 - WARNING -  * Debugger is active!
2025-07-03 21:28:30,593 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:28:46,172 - INFO - 192.168.1.5 - - [03/Jul/2025 21:28:46] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:29:27,623 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:29:27,625 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:29:27,634 - INFO -  * Restarting with stat
2025-07-03 21:29:32,923 - WARNING -  * Debugger is active!
2025-07-03 21:29:32,932 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:29:47,102 - INFO - 192.168.1.5 - - [03/Jul/2025 21:29:47] "GET / HTTP/1.1" 200 -
2025-07-03 21:29:47,341 - INFO - 192.168.1.5 - - [03/Jul/2025 21:29:47] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-03 21:29:50,375 - INFO - 192.168.1.5 - - [03/Jul/2025 21:29:50] "[35m[1mGET /submit HTTP/1.1[0m" 500 -
2025-07-03 21:29:50,520 - INFO - 192.168.1.5 - - [03/Jul/2025 21:29:50] "GET /submit?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-07-03 21:29:50,562 - INFO - 192.168.1.5 - - [03/Jul/2025 21:29:50] "GET /submit?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-07-03 21:29:50,675 - INFO - 192.168.1.5 - - [03/Jul/2025 21:29:50] "GET /submit?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-07-03 21:30:05,981 - INFO - 192.168.1.5 - - [03/Jul/2025 21:30:05] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:30:24,248 - INFO - 192.168.1.5 - - [03/Jul/2025 21:30:24] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:31:40,011 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:31:40,013 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:31:40,021 - INFO -  * Restarting with stat
2025-07-03 21:31:45,344 - WARNING -  * Debugger is active!
2025-07-03 21:31:45,354 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:32:02,161 - INFO - 192.168.1.5 - - [03/Jul/2025 21:32:02] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:35:15,600 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-03 21:35:15,602 - INFO - [33mPress CTRL+C to quit[0m
2025-07-03 21:35:15,611 - INFO -  * Restarting with stat
2025-07-03 21:35:20,910 - WARNING -  * Debugger is active!
2025-07-03 21:35:20,919 - INFO -  * Debugger PIN: 103-585-940
2025-07-03 21:35:30,342 - INFO - 192.168.1.5 - - [03/Jul/2025 21:35:30] "GET /admin HTTP/1.1" 200 -
2025-07-03 21:35:48,748 - INFO - 192.168.1.5 - - [03/Jul/2025 21:35:48] "GET / HTTP/1.1" 200 -
2025-07-03 21:35:48,961 - INFO - 192.168.1.5 - - [03/Jul/2025 21:35:48] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-03 21:35:53,451 - INFO - 192.168.1.5 - - [03/Jul/2025 21:35:53] "GET /submit HTTP/1.1" 200 -
2025-07-03 21:35:53,641 - INFO - 192.168.1.5 - - [03/Jul/2025 21:35:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-03 21:35:59,800 - INFO - 192.168.1.5 - - [03/Jul/2025 21:35:59] "GET /submit HTTP/1.1" 200 -
2025-07-03 21:35:59,929 - INFO - 192.168.1.5 - - [03/Jul/2025 21:35:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-04 19:27:59,174 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-07-04 19:27:59,175 - INFO - [33mPress CTRL+C to quit[0m
2025-07-04 19:28:42,693 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:5000
 * Running on https://192.168.1.20:5000
2025-07-04 19:28:42,695 - INFO - [33mPress CTRL+C to quit[0m
2025-07-04 19:28:42,703 - INFO -  * Restarting with stat
2025-07-04 19:28:47,999 - WARNING -  * Debugger is active!
2025-07-04 19:28:48,010 - INFO -  * Debugger PIN: 363-902-706
2025-07-04 20:43:09,956 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.20:5000
2025-07-04 20:43:09,957 - INFO - [33mPress CTRL+C to quit[0m
2025-07-04 20:43:09,967 - INFO -  * Restarting with stat
2025-07-04 20:43:15,264 - WARNING -  * Debugger is active!
2025-07-04 20:43:15,273 - INFO -  * Debugger PIN: 132-529-339
2025-07-04 20:49:53,424 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:49:53] code 400, message Bad request version ('¿ú£\x81\x9a±Ã°Ä4\x94\'·eíºµúÏ¬Î\x99¹ùLá\x89Èà\x93éb\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-04 20:49:53,426 - INFO - 112.199.132.115 - - [04/Jul/2025 20:49:53] "[35m[1m\x16\x03\x01\x07g\x01\x00\x07c\x03\x03e;©Þ\x19\x17\x12í\x14p`\x93\x90®\x88ÍûEÕÝ"Ë @S\x95¨?\x18³Vy ¿ú£\x81\x9a±Ã°Ä4\x94'·eíºµúÏ¬Î\x99¹ùLá\x89Èà\x93éb\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-04 20:49:53,444 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:49:53] code 400, message Bad request version ('¯\x86ÄÛY[W')
2025-07-04 20:49:53,446 - INFO - 112.199.132.115 - - [04/Jul/2025 20:49:53] "[35m[1m\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x03U×>\x17~\x02ü³þ\x8a)Äµ¯ò6\x85÷\x13ôó¢ö9ÂöBæ0å\x97Ô ¯\x86ÄÛY[W[0m" HTTPStatus.BAD_REQUEST -
2025-07-04 20:50:00,062 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:50:00] code 400, message Bad request version ('$C\x02!(Ç{Õb¬G§nGs+Q\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-04 20:50:00,064 - INFO - 112.199.132.115 - - [04/Jul/2025 20:50:00] "[35m[1m\x16\x03\x01\x07g\x01\x00\x07c\x03\x03æNUÂ\x9d\x04\x0b­\x1bNpåK1Ô\x18\x1f¿\x1f\x07\x9f´Z\x8dJ\x9b`ÇÙ,¸& @\x8eã¥BFQþ\x19g×¼\x078\x0c$C\x02!(Ç{Õb¬G§nGs+Q\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-04 20:50:00,081 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:50:00] code 400, message Bad request syntax ('\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x03½$\x9d\x1c')
2025-07-04 20:50:00,083 - INFO - 112.199.132.115 - - [04/Jul/2025 20:50:00] "[35m[1m\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x03½$\x9d\x1c[0m" HTTPStatus.BAD_REQUEST -
2025-07-04 20:50:01,391 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:50:01] code 400, message Bad request version ('<N.§y\x18-\x9c')
2025-07-04 20:50:01,393 - INFO - 112.199.132.115 - - [04/Jul/2025 20:50:01] "[35m[1m\x16\x03\x01\x07g\x01\x00\x07c\x03\x03â\x12àyÒ\x9f\x15onIK*,\x93\x8eïM\x07îD¼õÔm}G\x1fí\x7f\x0c3  <N.§y\x18-\x9c[0m" HTTPStatus.BAD_REQUEST -
2025-07-04 20:50:01,414 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:50:01] code 400, message Bad request version ('k\x94\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-04 20:50:01,416 - INFO - 112.199.132.115 - - [04/Jul/2025 20:50:01] "[35m[1m\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x03U°Õ¸4Ê¬\x1aOs\x0fC¯\x9cÀT`ßi\x12\x83_.Ê}¥\x0eKN\x9cO) ¯_4ì ê\x96°ÿr\x81Äs\x0fÏ#\x83bËÝ`¿í·4Ùç2\x80\x1ck\x94\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-04 20:50:04,988 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:50:04] code 400, message Bad request version ('i\x17¿\x0f\x05m\x8aÂ6\x94/O\x04¦ÔCÛ¾Ãè\x0fÚJ\x08·\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-04 20:50:04,989 - INFO - 112.199.132.115 - - [04/Jul/2025 20:50:04] "[35m[1m\x16\x03\x01\x07g\x01\x00\x07c\x03\x03\x0d#ÚÊ\x8aåp\\®¨Pöh\x1d8t^\x9b µ¢.o\x98ã\x05%'Ëp¾¯ g\x8ad.¸\x9d\x0di\x17¿\x0f\x05m\x8aÂ6\x94/O\x04¦ÔCÛ¾Ãè\x0fÚJ\x08·\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-04 20:50:05,006 - ERROR - 112.199.132.115 - - [04/Jul/2025 20:50:05] code 400, message Bad request version ('\x91¼»Ó\x06yfô\x84\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-04 20:50:05,008 - INFO - 112.199.132.115 - - [04/Jul/2025 20:50:05] "[35m[1m\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x03×­ö\x9dpî\x86WÜÊ\x8aG¦ ¯[<Æò:ào\x99\x88+ÿ\x183sí\x8e\x90 1ÞÔqáÏU¬\x88RÜ#Éé\x98ó/õç!\x01p\x09\x91¼»Ó\x06yfô\x84\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 20:52:58,867 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-07-05 20:52:58,869 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 20:54:04,971 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-07-05 20:54:04,973 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 20:54:40,379 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-07-05 20:54:40,381 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 21:01:23,054 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 203, in upload
    file_path = os.path.join(UPLOAD_FOLDER, file.filename)
NameError: name 'file' is not defined
2025-07-05 21:04:37,492 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 203, in upload
    file_path = os.path.join(UPLOAD_FOLDER, file.filename)
NameError: name 'file' is not defined
2025-07-05 21:08:24,131 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 203, in upload
    file_path = os.path.join(UPLOAD_FOLDER, file.filename)
NameError: name 'file' is not defined
2025-07-05 21:11:24,912 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 211, in upload
    current_user.points += 5
AttributeError: 'AnonymousUserMixin' object has no attribute 'points'
2025-07-05 21:20:35,298 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-07-05 21:20:35,300 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 21:21:48,374 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-07-05 21:21:48,376 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 21:22:24,594 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.20:5000
2025-07-05 21:22:24,595 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 21:22:24,603 - INFO -  * Restarting with stat
2025-07-05 21:22:29,893 - WARNING -  * Debugger is active!
2025-07-05 21:22:29,902 - INFO -  * Debugger PIN: 177-471-577
2025-07-05 21:22:29,986 - ERROR - 112.199.132.115 - - [05/Jul/2025 21:22:29] code 400, message Bad request version ('dNnÄp,Ä[0àà\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 21:22:29,988 - INFO - 112.199.132.115 - - [05/Jul/2025 21:22:29] "[35m[1m\x16\x03\x01\x07g\x01\x00\x07c\x03\x03ú\x02ÉµÇ\x93\x02r%ó}\x92<ÏDî¼Cü®nGê V¬¼\x98\x97Õ°\x00 TV\x1fÔ\x9b.0¢Çº7É\x05Ô\x18\x06Â\x05\x01¯\x1ddNnÄp,Ä[0àà\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 21:22:30,809 - ERROR - 112.199.132.115 - - [05/Jul/2025 21:22:30] code 400, message Bad request version ('Oß\x7fÚà:q°\x9c\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 21:22:30,811 - INFO - 112.199.132.115 - - [05/Jul/2025 21:22:30] "[35m[1m\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x03\x1b\x9e§!\x19{¦BV^;\x0b$`V\x03J¤\x16\x0b\x03É\x02D\x90 [\x06Z7?ì u\x13ºÛôo\x15W­\x0bFQuÕ+.x\x1c2=@\x09\x0bOß\x7fÚà:q°\x9c\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 21:22:48,427 - ERROR - 112.199.132.115 - - [05/Jul/2025 21:22:48] code 400, message Bad request version (':¾\x86¦ý8\x94')
2025-07-05 21:22:48,429 - INFO - 112.199.132.115 - - [05/Jul/2025 21:22:48] "[35m[1m\x16\x03\x01\x07g\x01\x00\x07c\x03\x03à\x84È W;\\v2t´@[E\x84Õô\x90[\x80ït\x14\x84/¯GwÇÃi\x06 :¾\x86¦ý8\x94[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 21:22:48,445 - ERROR - 112.199.132.115 - - [05/Jul/2025 21:22:48] code 400, message Bad request version ('\x8bÆ¡r¤°\x87Ç\x00¸]Â\x13')
2025-07-05 21:22:48,447 - INFO - 112.199.132.115 - - [05/Jul/2025 21:22:48] "[35m[1m\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x031;ÛÑ2\x0c×@9¸¥eQ÷Ky«µÅ\x16Öô¤\\¢köV\x941Uu \x8bÆ¡r¤°\x87Ç\x00¸]Â\x13[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 21:22:53,643 - ERROR - 112.199.132.115 - - [05/Jul/2025 21:22:53] code 400, message Bad request version ('|Ä/3\x90¹')
2025-07-05 21:22:53,648 - INFO - 112.199.132.115 - - [05/Jul/2025 21:22:53] "[35m[1m\x16\x03\x01\x07g\x01\x00\x07c\x03\x03Ïñ\x94\x12\x85\x1fX\x87n{\x09û\x1ee ¶\x0d|Ä/3\x90¹[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 21:22:53,665 - ERROR - 112.199.132.115 - - [05/Jul/2025 21:22:53] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x035ø\x93Øú-k\x8e\x9d}Ã¦u[¾×\x89ÎDúî¤\x08ÂU!ÏUØ*ó\x0e')
2025-07-05 21:22:53,666 - INFO - 112.199.132.115 - - [05/Jul/2025 21:22:53] "[35m[1m\x16\x03\x01\x02\x96\x01\x00\x02\x92\x03\x035ø\x93Øú-k\x8e\x9d}Ã¦u[¾×\x89ÎDúî¤\x08ÂU!ÏUØ*ó\x0e \x8f\x87\x1aòì\x19\x84\x12¯,ï\x95[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 21:23:35,813 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:35] "GET / HTTP/1.1" 200 -
2025-07-05 21:23:36,070 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:36] "GET /static/ironing.jpg HTTP/1.1" 200 -
2025-07-05 21:23:36,350 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-05 21:23:38,917 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:38] "GET /login HTTP/1.1" 200 -
2025-07-05 21:23:49,125 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:49] "[32mPOST /login HTTP/1.1[0m" 302 -
2025-07-05 21:23:49,445 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:49] "GET / HTTP/1.1" 200 -
2025-07-05 21:23:49,536 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:49] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-05 21:23:53,352 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:53] "GET /submit HTTP/1.1" 200 -
2025-07-05 21:23:54,831 - INFO - 112.199.132.115 - - [05/Jul/2025 21:23:54] "POST /upload HTTP/1.1" 200 -
2025-07-05 21:24:12,914 - INFO - 112.199.132.115 - - [05/Jul/2025 21:24:12] "POST /upload HTTP/1.1" 200 -
2025-07-05 21:24:20,932 - INFO - 112.199.132.115 - - [05/Jul/2025 21:24:20] "GET /admin HTTP/1.1" 200 -
2025-07-05 21:24:26,276 - INFO - 112.199.132.115 - - [05/Jul/2025 21:24:26] "GET /forum HTTP/1.1" 200 -
2025-07-05 21:25:29,319 - INFO - 112.199.132.115 - - [05/Jul/2025 21:25:29] "[32mPOST /forum HTTP/1.1[0m" 302 -
2025-07-05 21:25:29,384 - INFO - 112.199.132.115 - - [05/Jul/2025 21:25:29] "GET /forum HTTP/1.1" 200 -
2025-07-05 21:25:47,804 - INFO - 112.199.132.115 - - [05/Jul/2025 21:25:47] "GET /badges HTTP/1.1" 200 -
2025-07-05 21:25:48,062 - INFO - 112.199.132.115 - - [05/Jul/2025 21:25:48] "[33mGET /static/images/badges/silver.jpg HTTP/1.1[0m" 404 -
2025-07-05 22:55:45,962 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.20:5000
2025-07-05 22:55:45,964 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 22:55:45,973 - INFO -  * Restarting with stat
2025-07-05 22:55:51,288 - WARNING -  * Debugger is active!
2025-07-05 22:55:51,297 - INFO -  * Debugger PIN: 146-131-811
2025-07-05 23:00:22,358 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.20:5000
2025-07-05 23:00:22,363 - INFO - [33mPress CTRL+C to quit[0m
2025-07-05 23:00:22,387 - INFO -  * Restarting with stat
2025-07-05 23:00:35,452 - WARNING -  * Debugger is active!
2025-07-05 23:00:35,460 - INFO -  * Debugger PIN: 205-964-937
2025-07-05 23:00:35,865 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:35] "GET / HTTP/1.1" 200 -
2025-07-05 23:00:36,056 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-05 23:00:36,115 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:36] "GET /static/ironing.jpg HTTP/1.1" 200 -
2025-07-05 23:00:42,390 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:42] "GET /about HTTP/1.1" 200 -
2025-07-05 23:00:44,193 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:44] "[32mGET /submit HTTP/1.1[0m" 302 -
2025-07-05 23:00:44,244 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:44] "GET /login?next=/submit HTTP/1.1" 200 -
2025-07-05 23:00:50,424 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:50] "POST /login?next=/submit HTTP/1.1" 200 -
2025-07-05 23:00:55,341 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:55] "GET / HTTP/1.1" 200 -
2025-07-05 23:00:55,399 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:55] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:00:56,538 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:56] "[32mGET /badges HTTP/1.1[0m" 302 -
2025-07-05 23:00:56,585 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:56] "GET /login?next=/badges HTTP/1.1" 200 -
2025-07-05 23:00:58,165 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:58] "GET / HTTP/1.1" 200 -
2025-07-05 23:00:58,235 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:58] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:00:59,366 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:59] "GET /rewards HTTP/1.1" 200 -
2025-07-05 23:00:59,462 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:59] "GET /static/michaelsoft.jpg HTTP/1.1" 200 -
2025-07-05 23:00:59,515 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:59] "GET /static/pear.jpg HTTP/1.1" 200 -
2025-07-05 23:00:59,526 - INFO - 192.168.1.23 - - [05/Jul/2025 23:00:59] "GET /static/goggle.jpg HTTP/1.1" 200 -
2025-07-05 23:01:01,567 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:01] "GET /rewards HTTP/1.1" 200 -
2025-07-05 23:01:01,675 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:01] "[36mGET /static/michaelsoft.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:01:01,693 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:01] "[36mGET /static/pear.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:01:01,730 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:01] "[36mGET /static/goggle.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:01:02,081 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:02] "GET /login HTTP/1.1" 200 -
2025-07-05 23:01:12,519 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:12] "GET / HTTP/1.1" 200 -
2025-07-05 23:01:12,554 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:12] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:01:47,420 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:47] "GET /about HTTP/1.1" 200 -
2025-07-05 23:01:57,242 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:57] "[32mGET /submit HTTP/1.1[0m" 302 -
2025-07-05 23:01:57,265 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:57] "GET /login?next=/submit HTTP/1.1" 200 -
2025-07-05 23:01:58,783 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:58] "GET / HTTP/1.1" 200 -
2025-07-05 23:01:58,816 - INFO - 192.168.1.23 - - [05/Jul/2025 23:01:58] "[36mGET /static/ironing.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:03:38,680 - INFO - 192.168.1.23 - - [05/Jul/2025 23:03:38] "GET /rewards HTTP/1.1" 200 -
2025-07-05 23:03:38,737 - INFO - 192.168.1.23 - - [05/Jul/2025 23:03:38] "[36mGET /static/michaelsoft.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:03:38,759 - INFO - 192.168.1.23 - - [05/Jul/2025 23:03:38] "[36mGET /static/pear.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:03:38,763 - INFO - 192.168.1.23 - - [05/Jul/2025 23:03:38] "[36mGET /static/goggle.jpg HTTP/1.1[0m" 304 -
2025-07-05 23:04:15,224 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request version ('«<\x10ÉJ\x1bh\x88y\x8f[Òéö\x9cýìÖ"®¨\x88\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 23:04:15,232 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03^\x13}\x0fÂ=1Ö×Õ¢\x91Ô¹\x81ÑM ñ\x16Ìw\x17\x0d¦aïêL\x8cúà ¸ËHW\x19V\x87]4\x09«<\x10ÉJ\x1bh\x88y\x8f[Òéö\x9cýìÖ"®¨\x88\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:15,316 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request version ('v°\x16N3A\x0e0ª\x84m¤Ô\x96<\x13?\x1a1ðì\x87;\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 23:04:15,318 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x032>Xh©\x17å§GY:f8å\x0eÍ"zÚé70Â¦×,Û\x17¿ü\x9b´ \x8cÊ"\x8a3J/Ö\x1dv°\x16N3A\x0e0ª\x84m¤Ô\x96<\x13?\x1a1ðì\x87;\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:15,464 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request version ('ñ}\x1aêåRl\x03$ê\x0e\x13\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 23:04:15,466 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03YôMKu3\x9dÊ|C»5$¹tÒx\x1b%4å\x8c\x9dÐûm\x1a\x97!Æ$\x05 ³§ô?´ç\x84NÊ\x0dÈý!ÚN \x98³Ø\x0cñ}\x1aêåRl\x03$ê\x0e\x13\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:15,523 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request version ('åÂòr\x88Þy¢zàµ\x8cºBaÈY\\ùÑ\x8b\x12`K\x7fÓÁ3ì~e¸\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 23:04:15,525 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03\x8bÝ0\x80\x16V\x9b)ØfÕ×.\x88\x1fg\x91\x03\x9dØº\x87Në4Tîr¹\x92çS åÂòr\x88Þy¢zàµ\x8cºBaÈY\\ùÑ\x8b\x12`K\x7fÓÁ3ì~e¸\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:15,643 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request version ('½\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 23:04:15,645 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03í\x8f\x98Y\x9d¨ðÍ,\x98y&\x09´ \x84\x97¾:\x07`vº\x9f\x8f|²î\x1cµO  GÖnÇd\x0cüÉõ\x8d\x06,5é\x09\x8d$â\x1c#\x83ù³Rá]\x0fý\x19Î\x1d½\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:15,971 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request version ('\x90ÑCÃ1ø+ë\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 23:04:15,973 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03j\x8fd` Íö«¼\x04Ñ¦Ð\x1fos\x0b9e\x05áM\x16\x81ðAr\x80nÇ3À ÄS·\x17·\x84z%áå¶\\,Kº-8qÖÛ¼\x09\x1f \x90ÑCÃ1ø+ë\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:15,978 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request syntax ('\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03\x94i·û\x86KK\x8aÈVL!c4z\x9bC\x9fÊ4ð®[)aM\x92')
2025-07-05 23:04:15,980 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03\x94i·û\x86KK\x8aÈVL!c4z\x9bC\x9fÊ4ð®[)aM\x92[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:15,987 - ERROR - 112.199.132.115 - - [05/Jul/2025 23:04:15] code 400, message Bad request version ('V¢Ðå\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
2025-07-05 23:04:15,989 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:15] "[35m[1m\x16\x03\x01\x02\x92\x01\x00\x02\x8e\x03\x03ÒùV¿ÒýªF¾ \x84¡p§³Hó\x93ëoá6\x16\x8d_>¾\x1a9L.\x15 ,%{:\x0c\x09³ù·×[ül\x13Æ\x0e\x01\x94\x7fîÏ\x05\x1b¨\x07E\x03\x1dV¢Ðå\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À[0m" HTTPStatus.BAD_REQUEST -
2025-07-05 23:04:20,915 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:20] "GET / HTTP/1.1" 200 -
2025-07-05 23:04:20,967 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:20] "GET /static/ironing.jpg HTTP/1.1" 200 -
2025-07-05 23:04:21,059 - INFO - 112.199.132.115 - - [05/Jul/2025 23:04:21] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-07-05 23:05:53,513 - INFO - 112.199.132.115 - - [05/Jul/2025 23:05:53] "GET / HTTP/1.1" 200 -
2025-07-05 23:05:53,541 - INFO - 112.199.132.115 - - [05/Jul/2025 23:05:53] "GET /static/ironing.jpg HTTP/1.1" 200 -
2025-07-07 19:31:49,404 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
2025-07-07 19:35:04,109 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
2025-07-07 19:35:26,648 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
2025-07-07 19:36:23,959 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
2025-07-07 19:37:21,893 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
2025-07-07 19:38:19,557 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
2025-07-07 19:39:09,149 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
2025-07-10 19:45:34,038 - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 68, in register
    db.session.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4481, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (username, password, points, role) VALUES (?, ?, ?, ?)]
[parameters: ('LucarioUltim8te', 'scrypt:32768:8:1$QdAIvDKt4FhPxfds$0dfe43d912b1219f37c4f2ccfdf8319578e12b719144bf2e5a293c88fd83cc60856ac45c1b9cd5955586d4175f850c46e1e83a04ada3b3386adffcaf255921b0', 0, 'user')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-10 19:46:10,168 - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 68, in register
    db.session.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4481, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (username, password, points, role) VALUES (?, ?, ?, ?)]
[parameters: ('LucarioUltim8te', 'scrypt:32768:8:1$bzV0IEYpE50ARmF8$c2b3322db9b85c709055036b344045776f51abefffa5a6ebe9ddda856df1c656143fff91bc98b6d0cda132912ef8bd182c47a5a17caa254f96255a3abb109662', 0, 'user')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-10 20:03:30,021 - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 68, in register
    db.session.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4481, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO user (username, password, points, role) VALUES (?, ?, ?, ?)]
[parameters: ('yuhann', 'scrypt:32768:8:1$ay8CsaoDeP1ROSKv$6bbcff87a2b6e7180a491beeacd4add0237c5b2cbe2409d6b76fa2bcb016aaf12e0292abb62a2e2a4bdf548dc2449e296edc96211805c5baf62aa5974ad9f9c7', 0, 'user')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-10 20:05:12,309 - ERROR - Exception on /admin [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/ironing/app.py", line 123, in admin_dashboard
    abort(403)
NameError: name 'abort' is not defined
2025-07-10 20:14:07,268 - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 68, in register
    db.session.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4481, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (username, password, points, role) VALUES (?, ?, ?, ?)]
[parameters: ('WangYuhao', 'scrypt:32768:8:1$pa79Zp71nTQJNOzU$b70881965bf5447bc1f6252e1474307d57aacb7d76b9f116b3576e6b57bd8139246bae2022d18c9d5d0616b33e75ea0cbf736c20f1fc03e8c339ad45ead9594e', 0, 'user')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-14 16:51:07,918 - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 68, in register
    db.session.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4481, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (username, password, points, role) VALUES (?, ?, ?, ?)]
[parameters: ('WangYuhao', 'scrypt:32768:8:1$vq3kBLCnBrpn8bvn$e18b934d7bbb3369d3a5dc8ef34cf525f114931d5f96c01de8ffc31484f84ff835ba44ba314a26dbf07d28e4e634cfbfd60fb2e4f10fa8f75f0a628dc9ee1e9e', 0, 'user')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-07-14 16:51:12,558 - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 68, in register
    db.session.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4481, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (username, password, points, role) VALUES (?, ?, ?, ?)]
[parameters: ('WangYuhao', 'scrypt:32768:8:1$c7Ygo0SNxGSGyLx8$1f58e376dcfecd76d8ed575ef81b85baf0a4e42763c2195f584776d9c972ae74d7466252003231f57c5606b2663151784516291651c8fa3e61f255272e339acd', 0, 'user')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-08-22 15:54:08,022 - ERROR - Exception on /trigger-error/500 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 241, in trigger_error
    raise RuntimeError("This is a simulated 500 error.")
RuntimeError: This is a simulated 500 error.
2025-08-22 15:54:16,452 - ERROR - Exception on /trigger-error/403 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/debian/ironing/app.py", line 244, in trigger_error
    abort(403)
NameError: name 'abort' is not defined
